spring:
  main:
    allow-circular-references: true

  application:
    name: nk-social-media

  datasource:
    url: jdbc:postgresql://localhost:5434/Auth
    username: Nihad
    password: Nihad2258@.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  security:
    secretKey: "b486a866017febebba8371d6df2de2c2835710ae20e3450595afa63b4bfa94b3cb0d313e028c326d7078dc4bb1d69c770c1aabd8"